# Generated by Django 5.0.3 on 2024-05-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ponte', models.CharField(max_length=50)),
                ('peso_linear', models.FloatField(blank=True, null=True)),
                ('peso_metade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_barra', models.CharField(max_length=50)),
                ('cm', models.FloatField()),
                ('esforco_interno', models.FloatField()),
                ('tipo', models.CharField(choices=[('T', 'Tração'), ('C', 'Compressão')], max_length=1)),
                ('n_fios', models.FloatField(blank=True, null=True)),
                ('n_fios_revisado', models.FloatField(blank=True, null=True)),
                ('ponte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponte.ponte')),
            ],
            options={
                'verbose_name_plural': 'Barras',
            },
        ),
    ]
