# Generated by Django 5.0.3 on 2024-05-12 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ponte', models.CharField(max_length=50)),
                ('peso_linear', models.FloatField(null=True)),
                ('peso_metade', models.FloatField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, default='', upload_to='ponte/covers/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cm', models.FloatField(null=True)),
                ('esforco_interno', models.FloatField(null=True)),
                ('tipo', models.CharField(choices=[('T', 'Tração'), ('C', 'Compressão')], max_length=1)),
                ('n_fios', models.FloatField(null=True)),
                ('n_fios_revisados', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ponte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponte.ponte')),
            ],
            options={
                'verbose_name_plural': 'Barras',
            },
        ),
    ]
