# Generated by Django 5.0.3 on 2024-05-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponte',
            name='peso_linear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponte',
            name='peso_metade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
