# Generated by Django 5.0.3 on 2024-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0002_alter_ponte_peso_linear_alter_ponte_peso_metade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponte',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
