# Generated by Django 5.0.3 on 2024-05-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0002_alter_barra_n_fios_alter_ponte_peso_linear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barra',
            name='n_fios',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barra',
            name='tipo',
            field=models.CharField(choices=[('T', 'Tração'), ('C', 'Compressão')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ponte',
            name='peso_linear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponte',
            name='peso_metade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
