# Generated by Django 5.0.3 on 2024-05-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0003_alter_ponte_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barra',
            name='n_fios',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barra',
            name='n_fios_revisados',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
