# Generated by Django 5.0.3 on 2024-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponte', '0003_alter_barra_n_fios_alter_barra_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barra',
            name='n_fios_revisado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
